joint_map:
    1: arm_left_1_joint
    2: arm_left_2_joint
    3: arm_left_3_joint
    4: arm_left_4_joint
    5: arm_left_5_joint
    6: arm_left_6_joint
    7: arm_left_7_joint
    8: arm_right_1_joint
    9: arm_right_2_joint
    10: arm_right_3_joint
    11: arm_right_4_joint
    12: arm_right_5_joint
    13: arm_right_6_joint
    14: arm_right_7_joint
    15: head_1_joint
    16: head_2_joint
    17: leg_left_1_joint
    18: leg_left_2_joint
    19: leg_left_3_joint
    20: leg_left_4_joint
    21: leg_left_5_joint
    22: leg_left_6_joint
    23: leg_right_1_joint
    24: leg_right_2_joint
    25: leg_right_3_joint
    26: leg_right_4_joint
    27: leg_right_5_joint
    28: leg_right_6_joint
    29: torso_1_joint
    30: torso_2_joint
